# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WellRESTed
email: pjdietz@gmail.com
description: >
    WellRESTed is a library for creating RESTful APIs and websites
    in PHP that provides abstraction for HTTP messages, a powerful middleware
    system, and a flexible router.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wellrested.org" # the base hostname & protocol for your site
twitter_username: pjdietz
github_username:  pjdietz

# Build settings
markdown: kramdown
